filter:
  excluded_paths:
    - "Tests/*"

build:
  nodes:
    coverage:
      tests:
        override:
          - command: composer run-script quality
            coverage:
              file: reports/coverage-clover.xml
              format: clover