language: php
os: linux
dist: bionic
php:
  - '7.4'
  - '8.0'

env:
  - LOWEST=""
  - LOWEST="--prefer-lowest"

install:
  - composer update ${LOWEST-install} --prefer-stable

script:
  - composer run-script quality